In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/complete_enron.csv')

,Unnamed: 0,index,content,fcontent,topic,vader_sentiment,vader_sentiment_bin,Topic
0,0,0,Here is our forecast\n\n,['forecast'],"[(0, 0.012501605), (1, 0.012501605), (2, 0.012...",0.000000,Neutral,Modern History
1,1,1,Traveling to have a business meeting takes the...,"['travel', 'business', 'meeting', 'take', 'fun...","[(0, 0.15656357), (1, 0.03257292), (2, 0.01856...",0.217700,Slightly Positive,Government
2,2,2,test successful. way to go!!!,"['test', 'successful', 'way']","[(10, 0.2562595), (34, 0.5062273)]",0.195300,Slightly Positive,Literature
3,3,3,"Randy,\n\n Can you send me a schedule of the s...","['randy', 'send', 'schedule', 'salary', 'level...","[(6, 0.120515056), (18, 0.19427584), (19, 0.16...",0.000000,Neutral,Engineering
4,4,4,Let's shoot for Tuesday at 11:45.,"['let', 'shoot', 'tuesday']","[(15, 0.34167174), (37, 0.3415987)]",-0.340000,Moderately Negative,Journalism
...,...,...,...,...,...,...,...,...
92187,97680,98218,Effective 11/1/00 deliveries to Eastrans is 30...,"['effective', 'delivery', 'eastrans', 'mmbtudy...","[(9, 0.17084026), (18, 0.17078577), (19, 0.170...",0.476700,Moderately Positive,Nature
92188,97681,98219,"PW, \n\nHPL's spot and base purchases by zone ...","['pw', 'hpls', 'spot', 'base', 'purchase', 'zo...","[(8, 0.11305909), (11, 0.12829624), (15, 0.149...",0.000000,Neutral,Astronomy
92189,97682,98220,The schedule is attached. I will remind you a...,"['schedule', 'attach', 'remind', 'day', 'advan...","[(0, 0.36822718), (20, 0.09971282), (25, 0.202...",0.000000,Neutral,Winter Olympics
92190,97683,98221,Enron Methanol nominates the following natural...,"['enron', 'methanol', 'nominate', 'follow', 'n...","[(5, 0.2574057), (8, 0.07809814), (18, 0.33238...",0.612400,Very Positive,Engineering
92191,97684,98222,Attached is the November 2000 nomination for o...,"['attached', 'november', 'nomination', 'take',...","[(3, 0.1033487), (7, 0.2625391), (8, 0.0954066...",0.252867,Slightly Positive,Culture

The following code converts all the Enron emails into the required format for fine-tuning. It then samples 2,000 for the training dataset and 500 for the testing dataset.

In [6]:
emails = []
for i in range(len(df)):
    emails.append('<|endoftext|>\n' + 'Topic: ' + str(df['Topic'][i]) + '\n' + 'Sentiment: ' + df['vader_sentiment_bin'][i] + '\n' + 'Email: ' + str(df['content'][i]) + '\n<|endoftext|>\n')
full = pd.DataFrame(emails,columns=['text'])
training_df = full.sample(n=2000)
testing_df = full.sample(n=500)
st = ''
for i in range(len(training_df)):
    st = st + training_df.reset_index()['text'][i]
training_df.to_csv('../data/train.csv')
testing_df.to_csv('../data/test.csv')
full.to_csv('../data/full_train.csv')
f = open('../data/train.txt', 'w')
f.write(st)

1028266